const tournaments = [
  {
    year: "1950",
    host: "Brasil",
    title: "1950: O Maracanaço",
    stage: "Fase Final",
    result: "Brasil 1-2 Uruguai",
    finish: "Vice-Campeão",
    tag: "Vice-Campeão",
    short: "1950",
    summary:
      "Na primeira copa depois da Segunda Guerra, o Brasil precisava de apenas um empate para ser campeão. Com 200 mil pessoas no Maracanã, a virada do Uruguai no segundo tempo chocou o país e o Brasil foi vice em casa. ",
  },
  {
    year: "1954",
    host: "Suiça",
    title: "1954: A Batalha de Berna",
    stage: "Quartas de Final",
    result: "Brasil 2-4 Hungria",
    finish: "Quartas de Final",
    tag: "Quartas de Final",
    short: "1954",
    summary:
      "Vestindo a camisa amarela com calção azul pela primeira vez, O Brasil tentava superar o trauma de 1950. Brasil caiu para Hungria de Puskás e Kocsis em uma partida que ficou posteriormente conhecida como Batalha de Berna, por causa da briga que ocorreu após a partida.",
  },
  {
    year: "1958",
    host: "Suécia",
    title: "1958: Pelé e Garrincha surgem e Brasil é Campeão",
    stage: "Final",
    result: "Brasil 5-2 Suécia",
    finish: "Campeão",
    tag: "Campeão",
    short: "1958",
    champion: true,
    summary:
      "Na Suécia, o Brasil finalmente conquistou a sua primeira Copa do Mundo. Com Pelé e Garrinca virando titulares durante a Copa, a Seleção derrotou País de Gales, França e Suécia, e conquistou o título.",
  },
  {
    year: "1962",
    host: "Chile",
    title: "1962: A Copa do Garrincha",
    stage: "Final",
    result: "Brasil 3-1 Tchecoslováquia",
    finish: "Campeão",
    tag: "Campeão",
    short: "1962",
    champion: true,
    summary:
      "Depois de perder Pelé por lesão ainda na fase de grupos, Garrincha assumiu o protagonismo e conduziu a Seleção ao bicampeonato mundial. Até hoje, essa é a única Seleção a ganhar duas Copas seguidas.",
  },
  {
    year: "1966",
    host: "Inglaterra",
    title: "1966: Brasil cai na Fase de Groupos",
    stage: "Fase de Grupos",
    result: "1 vitória e 2 derrotas",
    finish: "Fase de Grupos",
    tag: "Fase de Grupos",
    short: "1966",
    summary:
      "Em uma das piores e mais decepcionantes participações no Mundial, o Brasil caiu ainda na fase de groupos. Na estreia, a única vitória sobre a Bulgária, no último jogo em que Garrincha e Pelé atuaram juntos, pois foi nesta partida que Pelé saiu de cmapo mais uma vez lesionado.",
  },
  {
    year: "1970",
    host: "México",
    title: "1970: A melhor seleção da história conquista o tri",
    stage: "Final",
    result: "Brasil 4-1 Itália",
    finish: "Campeão",
    tag: "Campeão",
    short: "1970",
    champion: true,
    summary:
      "Vitória em todos os jogos e uma média de mais de três gols por jogo, a Seleção Brasileira de 1970 é um dos maiores times da história. Comandada por Zagallo, com Pelé como protagonista, e com outros craques como Rivellino, Carlos Alberto Torres, Jairzinho e Tostão, a Seleção brasileira conquistou o tri em cima da Itália.",
  },
  {
    year: "1974",
    host: "Alemanha",
    title: "1974: Renovação após a era Pelé",
    stage: "Semi-Final",
    result: "Brasil 0-1 Polônia",
    finish: "Quarto lugar",
    tag: "Quarto",
    short: "1974",
    summary:
      "Sem Pelé, o Brasil passou por uma transição. Ainda assim, o Brasil conseguiu chegar na semi-final mas perdeu para a Holanda de Johann Cruyff por 2-0. Na disputa pelo terceiro lugar, a Seleção perdeu por 1-0 para a Polônia.",
  },
  {
    year: "1978",
    host: "Argentina",
    title: "1978: Invicto mas não campeão",
    stage: "Segunda Fase",
    result: "Brasil 2-1 Itália",
    finish: "Terceiro lugar",
    tag: "Terceiro",
    short: "1978",
    summary:
      "Na Argentina, o Brasil não perdeu nenhum jogo. a Seleção se classificou para a segunda fase da Copa e caiu no groupo da Argentina e ocorreu uma das maiores polêmicas da história das Copas. Brasil venceu a Polônia por 3-1, obrigando a Argentina a golear o Peru por mais de quatro gols. Resultado? 6-0 para a Argentina, que avançaram à final. Esta goleada ficou sob suspeita de ter sido 'arranjada'.",
  },
  {
    year: "1982",
    host: "Espanha",
    title: "1982: A Tragédia do Sarriá",
    stage: "Segunda Fase",
    result: "Brasil 2-3 Itália",
    finish: "Segunda fase",
    tag: "Segunda Fase",
    short: "1982",
    summary:
      "Considerada por muitos como a melhor seleção brasileira na história das Copas, o time era recheado de craques no ague como Zico, Sócrates, Falcão e Júnior, além de jogar um futebol que encantou o mundo. Mas foi eliminada pela Itália de Paolo Rossi, que fez um hat-trick na vitória em cima do Brasil por 3-2.",
  },
  {
    year: "1986",
    host: "México",
    title: "1986: Drama no México",
    stage: "Quartas de Final",
    result: "Brasil 1(3)-1(4) França",
    finish: "Quartas de Final",
    tag: "Quartas de Final",
    short: "1986",
    summary:
      "Mesmo começando a Copa com muita dificuldade, o Brasil conseguiu chegar nas Quartas de Finais contra a França. No segundo tempo, quando o placar ainda estana 1-1, Zico teve a oportunidade de colocar o Brasil na frente em uma cobrança de pênalti, mas ela foi defendida pelo goleiro Bats. A França acabou vencendo nos pênaltis por 4-3.",
  },
  {
    year: "1990",
    host: "Itália",
    title: "1990: Brasil cai para a Argentina",
    stage: "Oitavas de Final",
    result: "Brasil 0-1 Argentina",
    finish: "Oitavas de Final",
    tag: "Oitavas de Final",
    short: "1990",
    summary:
      "Brasil foi invicto em seu grupo mas não convenceu em nehuma das três vitórias. Após linda jogada de Maradona e com gol de Caniggia, o Brasil foi eliminado pela Argentina nas oitavas de final.",
  },
  {
    year: "1994",
    host: "Estados Unidos",
    title: "1994: Romário encerra jejum de 24 anos",
    stage: "Final",
    result: "Brasil 0(3)-0(2) Itália",
    finish: "Campeão",
    tag: "Campeão",
    short: "1982",
    champion: true,
    summary:
      "O Brasil não era um dos favoritos e confirmou sua classificação apenas na última rodada das Eliminatórias. Mas comandado por Romário e Bebeto, a Seleção ganhou o tetracampeonato em cima da Itália com um pênalti perdido de Baggio.",
  },
  {
    year: "1998",
    host: "França",
    title: "1998: Brasil chega a Final mais uma vez, mas é Vice",
    stage: "Final",
    result: "Brasil 0-3 França",
    finish: "Vice-Campeão",
    tag: "Vice-Campeão",
    short: "1998",
    summary:
      "Com Ronaldo sendo protagonista e melhor do mundo, o Brasil chegou a mais uma final. Mas contra a dona da casa França, o Brasil perdeu a final contra a França de Zidane. ",
  },
  {
    year: "2002",
    host: "Japão e Coreia do Sul",
    title: "2002: O Fenômeno se Redime",
    stage: "Final",
    result: "Brasil 2-0 Alemanha",
    finish: "Campeão",
    tag: "Campeão",
    short: "2002",
    champion: true,
    summary:
      "Vencendo todos os sete jogos que disputou, contando com grandes atuações de Rivaldo, Ronaldinho Gaúcho, Cafu, Roberto Carlos e do Ronaldo, que foi artilheiro da Copa, o Brasil conquistava o pentacampeonato mundial.",
  },
  {
    year: "2006",
    host: "Alemanha",
    title: "2006: O Quadrado Mágico não Brilha",
    stage: "Quartas de Final",
    result: "Brasil 0-1 França",
    finish: "Quartas de Final",
    tag: "Quartas de Final",
    short: "2006",
    summary:
      "O quadrado mágico composto por Ronaldo, Ronaldinho, Kaká e Adriano não correspondeu e foi decepcionante. A Seleção não convenceu e foi eliminada pela França nas quarats de finais com uma atuação mágica de Zidane.",
  },
  {
    year: "2010",
    host: "África do Sul",
    title: "2010: Brasil leva virada e é Eliminada",
    stage: "Quartas de Final",
    result: "Brasil 1-2 Holanda",
    finish: "Quartas de Final",
    tag: "Quartas de Final ",
    short: "2006",
    summary:
      "Um time forte coletivamente, a Seleção de Dunga teve uma uma boa Copa. Nas quartas de final, a Seleção fez seu melhor jogo mas foi eliminada pela Holanda de virada e Felipe Melo ainda foi expulso naquele jogo.",
  },
  {
    year: "2014",
    host: "Brasil",
    title: "2014: O Maior Vexame das Copas",
    stage: "Semi Final",
    result: "Brasil 1-7 Alemanha",
    finish: "Semi Final",
    tag: "Semi Final",
    short: "2014",
    summary:
      "Com Neymar como protagonista, a Seleção fez uma ótima primeira fase. Mas nas quartasde final, Neymar recebeu uma joelhada nas costas do lateral Zúñiga e foi cortado do restante da Copa. Na semifinal, em frente ao Mineirão lotado, a Seleção perdeu para a Alemanha de 7-1.",
  },
  {
    year: "2018",
    host: "Russía",
    title: "2018: O Brasil cai para a Geração Belga",
    stage: "Quartas de Final",
    result: "Brasi 1-2 Bélgica",
    finish: "Quartas de Final",
    tag: "Quartas de Final",
    short: "2018",
    summary:
      "Cotado como favorito para ser campeão, a Seleção de Tite tinha Neymar como seu principal nome. Mesmo não estando 100%, Neymar e Coutinho foram destaques da Seleção. Nas quartas de final, o duelo foi contra a Bélgica de De Bruyne e Hazard. A Bélgica abriu 2-0 no primeiro tempo e a Seleção não conseguiu reverter a diferença, perdendo por 2-1.",
  },
  {
    year: "2022",
    host: "Catar",
    title: "2022: O Brasil é surpreendido pela Croácia",
    stage: "Quartas de Final",
    result: "Brasil 1(2)-1(4) Croácia",
    finish: "Quartas de Final",
    tag: "Quartas de Final",
    short: "2022",
    summary:
      "como uma das favoritas, a Seleção de Tite fez uma boa Copa. Nas quartas de final, era favorito contra a Croácia. Neymar fez um golaço na prorrogação mas a Croácia acertou um contra-ataque faltando 4 minutos para acabar o jogo. O jogo foi para os pênaltis onde o Brasil perdeu para a Croácia.",
  },
]
